name = "gemini-balance-lite"
# 主入口
main = "src/index.js"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "GEMINI_RATE_LIMIT", id = "e05bffd293bd4aa6962d5dbfb77a3b24" }
]

[vars]
GEMINI_PROXY_CONFIG = '''
{
    "rateLimits": {
        "gemini-2.5-pro": 60,
        "gemini-2.5-flash": 10
    },
    "dailyCallLimits": {
        "gemini-2.5-pro": 45,
        "gemini-2.5-flash": 240
    }
}
'''

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
